Fix run action schedule

diff --git a/.github/workflows/run.yml b/.github/workflows/run.yml
--- a/.github/workflows/run.yml
+++ b/.github/workflows/run.yml
@@ -5,7 +5,7 @@ on:
     branches:
       - master
   schedule:
-    - cron: '0 * * * *'
+    - cron: '0 9,21 * * *'
 
 jobs:
   test:
@@ -15,35 +15,34 @@ jobs:
         python-version: [3.8]
 
     steps:
-    - name: Checkout codes
-      uses: actions/checkout@v2
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v2
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: Install dependencies
-      run: sudo apt install jq curl
-    - name: Install python dependencies
-      run: |
-        python -m pip install --upgrade pip
-        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-    - name: Get previous rss_database.csv
-      env:
-        GITHUB_REPO: ${{ github.repository }}
-      run: |
-        curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-          $(curl  -H "Accept: application/vnd.github.v3+json" \
-          https://api.github.com/repos/$GITHUB_REPO/actions/artifacts\?page\=1\&per_page\=1 \
-          | jq -r .artifacts\[0\].archive_download_url) -o rss_database.zip || echo "Previous rss_database.csv not found"
-    - name: Run code
-      env:
-        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
-        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
-      run: |
-        python main.py
-    - name: Upload rss_database.csv
-      uses: actions/upload-artifact@v2
-      with:
-        name: rss_database
-        path: rss_database.csv
-
+      - name: Checkout codes
+        uses: actions/checkout@v2
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v2
+        with:
+          python-version: ${{ matrix.python-version }}
+      - name: Install dependencies
+        run: sudo apt install jq curl
+      - name: Install python dependencies
+        run: |
+          python -m pip install --upgrade pip
+          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+      - name: Get previous rss_database.csv
+        env:
+          GITHUB_REPO: ${{ github.repository }}
+        run: |
+          curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            $(curl  -H "Accept: application/vnd.github.v3+json" \
+            https://api.github.com/repos/$GITHUB_REPO/actions/artifacts\?page\=1\&per_page\=1 \
+            | jq -r .artifacts\[0\].archive_download_url) -o rss_database.zip || echo "Previous rss_database.csv not found"
+      - name: Run code
+        env:
+          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
+          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+        run: |
+          python main.py
+      - name: Upload rss_database.csv
+        uses: actions/upload-artifact@v2
+        with:
+          name: rss_database
+          path: rss_database.csv
